In [13]:
import numpy as np
import matplotlib.pyplot as plt
"""
Functions for Exam
"""
from bayesian_classifiers import NaiveBayesClassifier
from string_format import str_to_nparray, str_to_binary_nparray
from association_mining import individualSupport, itemsetSupport, conf
from similaritymeasure import *
from explained_var import individual_explained_var, cum_explained_var
from multinomial_regression import class_probabilities
from K_means import kmeans
from adaboost import getAlpha, majorityVotingClassifier, updateWeights
from AUC_ROC import AUC_no_coords
from draw_dendogram import DrawDendogram
from KNN_density import density, ard
from neural_networks import NN_output
from NeuralNetwork import NeuralNetwork
from comparing_partitions import delta, countingMat, index
from knnCV import knn_CV
from probability_distributions import *

### Q3: PCA

In [2]:
X = """-0.6 -0.6 2.5 -0.1
-0.8 -0.3 -1 1.2
-0.7 0.3 -0.2 -0.1
1.4 1 0.1 -2.8
-0.2 0.8 -1.2 0.7"""
X = str_to_nparray(X)
V = """ 0.43 -0.26 0.22 -0.84
0.17 -0.37 0.81 0.42
0.33 0.88 0.34 -0.01
-0.82 0.14 0.42 -0.36"""
V = str_to_nparray(V)
X, V

(array([[-0.6, -0.6,  2.5, -0.1],
        [-0.8, -0.3, -1. ,  1.2],
        [-0.7,  0.3, -0.2, -0.1],
        [ 1.4,  1. ,  0.1, -2.8],
        [-0.2,  0.8, -1.2,  0.7]]),
 array([[ 0.43, -0.26,  0.22, -0.84],
        [ 0.17, -0.37,  0.81,  0.42],
        [ 0.33,  0.88,  0.34, -0.01],
        [-0.82,  0.14,  0.42, -0.36]]))

In [3]:
A = X@V
A

array([[ 0.547,  2.564,  0.19 ,  0.263],
       [-1.709, -0.393, -0.255,  0.124],
       [-0.234, -0.119, -0.021,  0.752],
       [ 3.101, -1.038, -0.024,  0.251],
       [-0.92 , -1.202,  0.49 ,  0.264]])

In [4]:
A

array([[ 0.547,  2.564,  0.19 ,  0.263],
       [-1.709, -0.393, -0.255,  0.124],
       [-0.234, -0.119, -0.021,  0.752],
       [ 3.101, -1.038, -0.024,  0.251],
       [-0.92 , -1.202,  0.49 ,  0.264]])

### Q4: PCA

In [5]:
s = np.array([3.7, 3.04, 0.56, 0.48])
individual_explained_var(s)


array([0.583, 0.394, 0.013, 0.01 ])

### Q6: Logistic Regression

### Q7: ANN

In [6]:
h = lambda x: np.tanh(x)

def feedforward(x):
    w11 = [2.2, 0.7, -0.3]
    w12 = [-0.2, 0.8, 0.4]
    w2 = [-0.7, 0.5]
    w0=2.2
    s = w2[0]*h(np.dot(x, np.array(w11))) + w2[1]*h(np.dot(x, np.array(w12))) + w0
    return h(s)


# top left
x1 = np.array([1, -2, 2])
# top right
x2 = np.array([1, 2, 2])
# bottom right
x3 = np.array([1, 2, -2])
# bottom left
x4 = np.array([1, -2, -2])

for x in [x1, x2, x3, x4]:
    print(feedforward(x))

0.9329964083023192
0.9634101227566055
0.9434820953882654
0.7953180737785034


### Q12: RLR

In [7]:
X = np.array([-3.4, -1.3, 0.5, 2.4, 4.2])
X = (X-np.mean(X))/np.std(X, ddof=1)
y_original = np.array([-2.9,-0.4, 0.7, 2.5, 4.5])
y = np.array([-2.9,-0.4, 0.7, 2.5, 4.5]).T
y -= np.mean(y)

# Finding optimal weights
a = X@X.T + 0.7
b = X.T@y
c=b/a
c


2.3855271282344326

In [8]:
np.mean(np.array([-2.9,-0.4, 0.7, 2.5, 4.5])), c

(0.8800000000000001, 2.3855271282344326)

In [9]:
c2 =  b/a
c2*(X[1])+np.mean(np.array([-2.9,-0.4, 0.7, 2.5, 4.5]))

-0.5403928682812784

In [10]:
c2

2.3855271282344326

In [11]:
w0 = np.mean(np.array([-2.9,-0.4, 0.7, 2.5, 4.5]))
w1=c
w0, w1
y_pred = w0 + w1*(-1.3-np.mean(X))/np.std(X, ddof=1)
y_pred

-2.2211852667047625

### Q13: Naïve-Bayes

In [14]:
mu_1, mu_2 = np.array([0.77, -0.41]).T, np.array([-0.91, 0.5]).T
sigma_1 = np.array([[0.29, -0.12], 
                    [-0.12, 0.55]])

sigma_2 = np.array([[0.32, -0.11],
                    [-0.11,1.12]])

x_test = np.array([0,0.7])

P_1 = multivariate_normal(mu_1, sigma_1, x_test, 2)
P_2 = multivariate_normal(mu_2, sigma_2, x_test, 2)
p_y_1 = 0.53
p_y_2 = 0.47
# Probability
p_y_1*P_1/(p_y_1*P_1 + p_y_2*P_2), p_y_2*P_2/(p_y_1*P_1 + p_y_2*P_2) 


(0.5799097919685753, 0.42009020803142477)

### Q15: Distances

In [ ]:
d = """
0 0
-0.4 -0.8 
-0.9 0.3 
0 0.9
1 -0.1
0.8 -0.7
0.1 0.8"""
d = str_to_nparray(d)

def makeDistanceMat(x, ord=2):
    """
    Given a list of vectors, compute the pairwise distance matrix.

    Used first in Fall 2017 exam.
    """
    n = len(x)
    D = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            D[i, j] = np.linalg.norm(x[i] - x[j], ord=ord)
    return D

d_1 = makeDistanceMat(d, ord=1)
d_2= makeDistanceMat(d, ord=2)
d_inf = makeDistanceMat(d, ord=np.inf)

In [ ]:
print(d_1)
print(np.round(d_2, 3))
print(d_inf)

### Q17: Dendrogram

In [ ]:
euc_dist = """0.0 2.6 2.8 2.1 0.8 1.7 3.9 3.8 4.1 4.2
2.6 0.0 1.8 2.3 2.7 1.4 1.9 1.7 2.0 2.2
2.8 1.8 0.0 1.2 2.9 2.1 2.2 1.6 2.3 2.0
2.1 2.3 1.2 0.0 2.4 1.8 2.6 2.5 3.0 2.9
0.8 2.7 2.9 2.4 0.0 2.0 4.2 4.0 4.4 4.5
1.7 1.4 2.1 1.8 2.0 0.0 2.4 2.6 2.7 3.0
3.9 1.9 2.2 2.6 4.2 2.4 0.0 1.2 0.6 1.3 
3.8 1.7 1.6 2.5 4.0 2.6 1.2 0.0 1.0 0.6
4.1 2.0 2.3 3.0 4.4 2.7 0.6 1.0 0.0 0.9
4.2 2.2 2.0 2.9 4.5 3.0 1.3 0.6 0.9 0.0"""
euc_dist = str_to_nparray(euc_dist)
DrawDendogram(euc_dist)

### Q18: AdaBoost

In [ ]:
initial_w = np.ones(6)/6
true_labels = np.array([2,2,1,2,1,1])
pred = np.array([2,2,2,1,2,2])

new_w = updateWeights(initial_w, pred, true_labels)
new_w


### Q19: KNN accuracy

In [ ]:
error = knn_CV(euc_dist, np.array([1,1,1,1,1,1,2,2,2,2]), 3)
error

### Q21: KDE anomalies

In [ ]:
vals = [-3, -1, 5, 6, -4, 2]
def kde_density(vals, sigma):
    """
    Returns the density of each point according to the KDE with the given sigma

    Parameters:
    vals (np.array): The values for which to calculate the density
    sigma (float): The standard deviation of the kernel

    Returns:
    np.array: The density of each point
    """

    density = np.zeros(len(vals))
    N = len(vals)
    for i in range(len(vals)):
        for j in range(len(vals)):
            if i != j:
                density[i] += np.exp(-0.5*(vals[i]-vals[j])**2/sigma**2)
        density[i] /= (N-1)*sigma*np.sqrt(2*np.pi)
    return density
k_d = kde_density(vals, np.sqrt(0.5))
k_d